# Generated by Django 4.2.5 on 2023-09-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lokation', models.CharField(blank=True, max_length=1000, null=True)),
                ('KundeID', models.CharField(blank=True, max_length=1000, null=True)),
                ('MAC', models.CharField(blank=True, max_length=1000, null=True)),
                ('Model', models.CharField(blank=True, max_length=1000, null=True)),
                ('S_N', models.CharField(blank=True, max_length=1000, null=True)),
                ('Navn', models.CharField(blank=True, max_length=1000, null=True)),
                ('Image', models.CharField(blank=True, max_length=1000, null=True)),
                ('GW_IP', models.CharField(blank=True, max_length=1000, null=True)),
                ('Noter', models.CharField(blank=True, max_length=1000, null=True)),
                ('Journalsystem', models.CharField(blank=True, max_length=1000, null=True)),
                ('Analyzers', models.CharField(blank=True, max_length=1000, null=True)),
                ('SIM', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
