# Generated by Django 4.2.5 on 2023-09-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='GW_IP',
            field=models.CharField(blank=True, db_column='GW_IP', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='KundeID',
            field=models.CharField(blank=True, db_column='KundeID', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='MAC',
            field=models.CharField(blank=True, db_column='MAC', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='S_N',
            field=models.CharField(blank=True, db_column='S_N', max_length=1000, null=True),
        ),
    ]
