# Generated by Django 4.2 on 2023-12-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Navn',
        ),
    ]
