# Generated by Django 4.2.5 on 2023-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_product_gw_ip_alter_product_kundeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='GW_IP',
            new_name='GatewayIP',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='MAC',
            new_name='MACadd',
        ),
        migrations.AlterField(
            model_name='product',
            name='SIM',
            field=models.CharField(blank=True, db_column='SIM', max_length=1000, null=True),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='SIM',
            new_name='SIMnr',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='S_N',
            new_name='SerieNr',
        ),
    ]
