# Generated by Django 4.2.5 on 2023-09-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_rename_gw_ip_product_gatewayip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='GatewayIP',
            field=models.TextField(blank=True, db_column='GW_IP', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='KundeID',
            field=models.TextField(blank=True, db_column='KundeID', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='MACadd',
            field=models.TextField(blank=True, db_column='MAC', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SIMnr',
            field=models.TextField(blank=True, db_column='SIM', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SerieNr',
            field=models.TextField(blank=True, db_column='S_N', max_length=1000, null=True),
        ),
    ]
