# Generated by Django 4.2 on 2024-01-09 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_alter_product_analyzers_alter_product_gatewayip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='AbonStart',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='CreatedDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
