# Generated by Django 4.2.5 on 2023-09-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_alter_product_gatewayip_alter_product_kundeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='GatewayIP',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='KundeID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='MACadd',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SIMnr',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SerieNr',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
