# Generated by Django 4.2.5 on 2023-10-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_company_alter_product_analyzers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
